# Generated by Django 5.0.1 on 2024-01-18 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_signup_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
