# Generated by Django 5.0.1 on 2024-01-18 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
