# Generated by Django 5.0.1 on 2024-01-18 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_signup_email_alter_signup_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'SignUp User'},
        ),
    ]
