# Generated by Django 5.0.1 on 2024-01-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_signup_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernamee', models.CharField(blank=True, max_length=20)),
                ('passwordd', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
