# Generated by Django 5.0.1 on 2024-01-19 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_product_alter_signin_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
