# Generated by Django 5.0.1 on 2024-01-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=6)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
